"""Project/worker scaffolding + detached loop launch.

``do_new`` writes the on-disk layout a project needs; ``spawn_loop`` launches a
worker's outer loop detached in its own process group. Both are libraries the
``danus`` CLI verbs (``danus.orchestration``) call — kept here beside the loop +
layout so the file names, config template, and launch mechanism live in one place.

Notes:
  - the codex MCP wiring launches the installed package ``python -m danus.gateway``
    (a pinned interface) rather than an absolute path to a server file;
  - the config template + defaults (verify URL, model) come from env at CALL time
    (with a built-in fallback default), not hard-wired at import time.
"""

from __future__ import annotations

import json
import os
import subprocess
import shutil
from pathlib import Path
from typing import Dict, List, Optional

from danus import codex
from danus import runtime

from . import layout as L

# --------------------------------------------------------------------------- #
# atomic file helpers                                                         #
# --------------------------------------------------------------------------- #

def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, path)


def _toml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def symlink(target: Path, link: Path) -> None:
    try:
        runtime.symlink_or_copy(target, link)
    except OSError:
        pass


# --------------------------------------------------------------------------- #
# codex config template + task placeholder                                    #
# --------------------------------------------------------------------------- #

# The MCP server is the installed danus gateway (role=worker) launched as a
# module — pinned interface (ARCHITECTURE.md §4): `python -m danus.gateway` +
# DANUS_ROLE. `command` comes from the shared runtime resolver, so explicit
# DANUS_PYTHON_BIN / DANUS_PY overrides are preserved. It is rewritten every time
# the loop starts, so a moved or rebuilt environment is picked up automatically.
_CODEX_CONFIG = """\
# Auto-generated by danus (rewritten each time the worker loop starts); do not hand-edit.
[mcp_servers.danus]
command = {python}
args = ["-m", "danus.gateway"]
# fact_submit blocks on the verify service (a cold-started codex that can reason
# for minutes on a hard proof); codex's default tool-call timeout is 120s, which
# would abort those legitimate long verifications. Match the verify HTTP timeout.
tool_timeout_sec = 3600

[mcp_servers.danus.env]
DANUS_PROJECT_DIR = {project_dir}
DANUS_AUTHOR = {author}
DANUS_ROLE = "worker"
DANUS_VERIFY_URL = {verify_url}
"""

_TASK_PLACEHOLDER = (
    "# Task\n\n(unassigned — the main agent writes your assignment here via "
    "`danus assign`; you read this file at the start of every round)\n"
)


def _verify_url() -> str:
    # each fact_submit POSTs here; the verify service spawns a fresh codex to
    # verify. Standard local endpoint by default; override with DANUS_VERIFY_URL.
    return os.environ.get("DANUS_VERIFY_URL", "http://127.0.0.1:8091/verify")


def _default_model() -> str:
    return codex.model()


def write_codex_config(wl: "L.WorkerLayout") -> None:
    """Write the worker's ``.codex/config.toml``, pinning the gateway ``command``
    to Danus's configured interpreter. Used at scaffold time and rewritten at every
    loop start so the gateway never relies on a bare ``python3`` from PATH."""
    atomic_write(wl.codex_config, _CODEX_CONFIG.format(
        python=_toml_str(runtime.current_python()),
        project_dir=_toml_str(str(wl.project_dir)),
        author=_toml_str(wl.name),
        verify_url=_toml_str(_verify_url()),
    ))


def worker_gateway_config_arg(wl: "L.WorkerLayout") -> str:
    """Inline the authoritative worker gateway regardless of ambient config."""
    py = json.dumps(runtime.current_python())
    project = json.dumps(str(wl.project_dir))
    author = json.dumps(wl.name)
    verify_url = json.dumps(_verify_url())
    return (
        f'mcp_servers.danus={{command={py},args=["-m","danus.gateway"],'
        f'tool_timeout_sec=3600,env={{DANUS_PROJECT_DIR={project},'
        f'DANUS_AUTHOR={author},DANUS_ROLE="worker",'
        f'DANUS_VERIFY_URL={verify_url}}}}}'
    )


# --------------------------------------------------------------------------- #
# do_new — scaffold a project                                                 #
# --------------------------------------------------------------------------- #

def do_new(project: str, roles: str = "high:3,xhigh:4",
           model: Optional[str] = None, *, problem: Optional[Path] = None) -> Dict:
    """Scaffold a project dir + one worker home per role. Refuses to clobber an
    existing project dir (no silent overwrite of a live fact graph). Returns
    ``{"project_dir", "workers"}``."""
    pdir = L.project_dir(project)
    if pdir.exists():
        raise SystemExit(f"project already exists: {pdir} (pick another name or remove it)")
    if problem is not None:
        if not Path(problem).is_file():
            raise SystemExit(f"problem file does not exist: {problem}")
        problem = Path(problem).resolve()
    role_pairs = L.parse_roles(roles)
    model = model or _default_model()

    L.workers_dir(project).mkdir(parents=True, exist_ok=True)
    (pdir / "global_memory").mkdir(exist_ok=True)
    (pdir / "fact_graph").mkdir(exist_ok=True)

    created: List[str] = []
    for worker, base in role_pairs:
        wl = L.WorkerLayout(L.worker_dir(project, worker))
        wl.local_memory.mkdir(parents=True, exist_ok=True)
        wl.logs.mkdir(exist_ok=True)

        # static contract + skills (symlinks stay in sync with the repo)
        symlink(L.worker_md(), wl.dir / "AGENTS.md")
        (wl.dir / ".agents").mkdir(exist_ok=True)
        symlink(L.worker_skills_dir(), wl.dir / ".agents" / "skills")

        # codex MCP wiring (role=worker)
        write_codex_config(wl)
        atomic_write(wl.task, _TASK_PLACEHOLDER)
        atomic_write(wl.role,
                     f"MODEL={model}\nREASONING_EFFORT={base}\nROLE={base}\nDANUS_AUTHOR={worker}\n")
        atomic_write(wl.status,
                     json.dumps({"worker": worker, "state": "created", "round": 0}, indent=2))
        created.append(worker)

    meta = {
        "name": project, "model": model, "roles": roles, "workers": created,
        "control_version": 2,
    }
    if problem is not None:
        shutil.copyfile(problem, pdir / "PROBLEM.md")
    from danus.control import ControlStore
    ControlStore(pdir).scaffold()
    atomic_write(pdir / "project.json", json.dumps(meta, ensure_ascii=False, indent=2))
    return {"project_dir": str(pdir), "workers": created, "control_version": 2}


def migrate_project(project: str) -> Dict:
    """Index a V1 project's existing stores, then atomically mark it V2.

    No target, route, obligation, or assignment is inferred. Existing facts and
    global memory stay in place; the original project metadata is preserved in
    the migration event. Runtime callers must check that workers are stopped
    before calling this function.
    """
    pdir = L.project_dir(project)
    meta_path = pdir / "project.json"
    if not pdir.is_dir():
        raise SystemExit(f"no such project: {project}")
    try:
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SystemExit(f"cannot migrate {project}: invalid project.json: {exc}") from exc
    if not isinstance(meta, dict):
        raise SystemExit(f"cannot migrate {project}: project.json must be an object")
    version = meta.get("control_version")
    if version == 2:
        from danus.control import ControlStore
        store = ControlStore(pdir)
        store.scaffold()
        with store._connect() as db:
            fact_count = int(db.execute("SELECT COUNT(*) FROM facts").fetchone()[0])
        return {"project": project, "migrated": False, "facts": fact_count,
                "generation": store.generation()}
    if version not in (None, 1):
        raise SystemExit(f"cannot migrate {project}: unsupported control_version {version!r}")

    from danus.control import ControlStore
    store = ControlStore(pdir)
    store.scaffold()
    if not store.events("project_migrated_from_v1"):
        store.append_event(
            "project_migrated_from_v1",
            source_control_version=version or 1,
            source_project_meta=meta,
        )
    migrated = dict(meta)
    migrated["control_version"] = 2
    migrated["migrated_from_control_version"] = version or 1
    atomic_write(meta_path, json.dumps(migrated, ensure_ascii=False, indent=2))
    with store._connect() as db:
        fact_count = int(db.execute("SELECT COUNT(*) FROM facts").fetchone()[0])
    return {"project": project, "migrated": True, "facts": fact_count,
            "generation": store.generation()}


# --------------------------------------------------------------------------- #
# spawn_loop — detached launch of one worker's outer loop                     #
# --------------------------------------------------------------------------- #

def spawn_loop(wdir: Path) -> int:
    """Launch ``python -m danus.execution <wdir>`` detached in its own process
    group (``start_new_session=True``) so ``danus stop --force`` can ``killpg``
    the loop *and* its in-flight codex child. Returns the child pid."""
    wl = L.WorkerLayout(wdir)
    wl.logs.mkdir(parents=True, exist_ok=True)
    logf = open(wl.logs / "loop.log", "a", encoding="utf-8")
    try:
        proc = runtime.spawn_detached(
            runtime.module_cmd("danus.execution", str(wdir)),
            stdout=logf, stderr=subprocess.STDOUT, stdin=subprocess.DEVNULL,
            cwd=str(wdir), env=os.environ.copy(),
        )
    finally:
        logf.close()
    return proc.pid
