"""Native configuration for the Codex backend used by every Danus role."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

from danus import codex

_MARKER = "# Generated by `uv run danus codex api`."


def _home() -> Path:
    value = os.environ.get("CODEX_HOME")
    if value:
        return Path(value).expanduser().resolve()
    return (Path.home() / ".codex").resolve()


def _provider_text(base_url: str, model: str) -> str:
    escaped_url = base_url.replace("\\", "\\\\").replace('"', '\\"')
    escaped_model = model.replace("\\", "\\\\").replace('"', '\\"')
    return (
        f"{_MARKER}\n"
        'model_provider = "danus_api"\n\n'
        "[model_providers.danus_api]\n"
        f'name = "Danus codex API ({escaped_model})"\n'
        f'base_url = "{escaped_url}"\n'
        'env_key = "DANUS_CODEX_API_KEY"\n'
        'wire_api = "responses"\n'
    )


def configure_api(*, force: bool = False) -> Path:
    base_url = os.environ.get("CODEX_API_BASE_URL", "").strip()
    key = os.environ.get("DANUS_CODEX_API_KEY", "").strip()
    model = os.environ.get("CODEX_API_MODEL", "gpt-5.5").strip() or "gpt-5.5"
    if not base_url:
        raise ValueError("CODEX_API_BASE_URL is not set in config/codex.env")
    if not key:
        raise ValueError("DANUS_CODEX_API_KEY is not set in config/codex.env")
    home = _home()
    config = home / "config.toml"
    if config.exists() and _MARKER not in config.read_text(encoding="utf-8") and not force:
        raise FileExistsError(
            f"refusing to replace non-Danus Codex config: {config}; pass --force to replace it"
        )
    home.mkdir(parents=True, exist_ok=True)
    temporary = config.with_suffix(".toml.tmp")
    temporary.write_text(_provider_text(base_url, model), encoding="utf-8")
    os.replace(temporary, config)
    return config


def _remove_generated_provider() -> bool:
    config = _home() / "config.toml"
    if not config.is_file() or _MARKER not in config.read_text(encoding="utf-8"):
        return False
    config.unlink()
    return True


def configure_parser(subparsers) -> None:
    parser = subparsers.add_parser("codex", help="configure or inspect the Codex backend")
    actions = parser.add_subparsers(dest="codex_action", required=True)
    api = actions.add_parser("api", help="write the BYO API model provider")
    api.add_argument("--force", action="store_true", help="replace a non-Danus config.toml")
    actions.add_parser("login", help="use Codex's ChatGPT login")
    actions.add_parser("status", help="show the configured backend and login status")


def dispatch(args) -> int:
    if args.codex_action == "api":
        try:
            config = configure_api(force=args.force)
        except (ValueError, FileExistsError) as exc:
            print(f"codex api: {exc}", file=sys.stderr)
            return 2
        print(f"configured danus_api in {config}")
        return 0

    codex_bin = codex.resolve_bin()
    command_env = codex.subprocess_env(codex_bin)
    if args.codex_action == "login":
        removed = _remove_generated_provider()
        if removed:
            print("removed the generated API provider")
        return subprocess.run([codex_bin, "login"], env=command_env, check=False).returncode

    config = _home() / "config.toml"
    if config.is_file() and _MARKER in config.read_text(encoding="utf-8"):
        print(
            "backend=api "
            f"home={_home()} base_url={os.environ.get('CODEX_API_BASE_URL', '')} "
            f"model={os.environ.get('CODEX_API_MODEL', 'gpt-5.5')}"
        )
        return 0
    result = subprocess.run(
        [codex_bin, "login", "status"], env=command_env, check=False
    )
    return result.returncode
